-- Business Settings Table Schema
-- Fresh table for storing company profile information

CREATE TABLE IF NOT EXISTS business_settings (
  id VARCHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
  company_name VARCHAR(255) NOT NULL,
  gstin VARCHAR(15) NULL COMMENT 'GST Identification Number',
  pan VARCHAR(10) NULL COMMENT 'Permanent Account Number',
  address TEXT NULL,
  city VARCHAR(100) NULL,
  state VARCHAR(100) NULL,
  pincode VARCHAR(6) NULL,
  phone VARCHAR(15) NULL,
  email VARCHAR(255) NULL,
  website VARCHAR(500) NULL,
  logo LONGTEXT NULL COMMENT 'Base64 encoded logo image',
  bank_name VARCHAR(100) NULL,
  bank_account VARCHAR(20) NULL,
  bank_ifsc VARCHAR(11) NULL,
  bank_branch VARCHAR(100) NULL,
  invoice_prefix VARCHAR(10) NOT NULL DEFAULT 'VE',
  quotation_prefix VARCHAR(10) NOT NULL DEFAULT 'QT',
  purchase_order_prefix VARCHAR(10) NOT NULL DEFAULT 'PO',
  challan_prefix VARCHAR(10) NOT NULL DEFAULT 'DC',
  terms_condition TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_business_settings (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default business settings for Viros Entrepreneurs
INSERT INTO business_settings (
  id,
  company_name,
  gstin,
  pan,
  address,
  city,
  state,
  pincode,
  phone,
  email,
  website,
  invoice_prefix,
  quotation_prefix,
  purchase_order_prefix,
  challan_prefix,
  terms_condition
) VALUES (
  UUID(),
  'Viros Entrepremeurs IT Solutions Pvt.',
  '07BWQPR5953N1ZF',
  'BWQPR5953N',
  '25/2, Block B, Molarband Extension Badarpur, New Delhi, Delhi 110044',
  'New Delhi',
  'Delhi',
  '110044',
  '7290969141',
  'info@virosentrepreneurs.com',
  'https://www.virosentrepreneurs.com/',
  'VE',
  'QT',
  'PO',
  'DC',
  'Warranty as per company guidlines'
) ON DUPLICATE KEY UPDATE
  company_name = VALUES(company_name),
  gstin = VALUES(gstin),
  pan = VALUES(pan),
  address = VALUES(address),
  city = VALUES(city),
  state = VALUES(state),
  pincode = VALUES(pincode),
  phone = VALUES(phone),
  email = VALUES(email),
  website = VALUES(website),
  invoice_prefix = VALUES(invoice_prefix),
  quotation_prefix = VALUES(quotation_prefix),
  purchase_order_prefix = VALUES(purchase_order_prefix),
  challan_prefix = VALUES(challan_prefix),
  terms_condition = VALUES(terms_condition),
  updated_at = CURRENT_TIMESTAMP;